### ISSUE TITLE
Fatal error: spawn W:\go-workspace\src\github.com\cristian-sima\contabilitate\node_modules\flow-bin\vendor\flow

### ISSUE THREAD

**Issue by cristian-sima** [larsonjj/grunt-flow#6]
Hi,

I have start using grunt-flow with this configuration:

```js
  options: {
    style: 'color'
  },
  es6 :{
    src: 'static/js-source/**/*.es6'
  }
```

but I get this 

![image](https://cloud.githubusercontent.com/assets/12199042/14919227/819e3b4c-0e30-11e6-8185-960eae6592f5.png)

**Comment by larsonjj** [comment]
Hey @cristian-sima,

Apologies for the late response. The `ENOENT` error in node means that the file or folder the system is looking for does not exist. It could also mean that you do not have the correct permissions on your machine to access those files/folders.

I am unable to replicate this issue on my machines, so it could be specific to your local environment. It also looks like you might be working within a remote/work environment, so you might need to contact your systems administrator to get the correct permissions.

Also be aware that `flow-bin` does not support Windows at the moment ([support in progress](https://github.com/flowtype/flow-bin/pull/24)), so that is most likely causing problems as well.

Hopefully this helps. Good luck!

**Comment by cristian-sima** [comment]
Is there any alternative for this or a workaround such that I can use grunt with flow-js on windows?
